package de.tfritsch.xearth;

import java.io.StringWriter;
import java.io.Writer;

import javax.xml.bind.JAXB;

import org.custommonkey.xmlunit.XMLAssert;
import org.custommonkey.xmlunit.XMLUnit;
import org.junit.BeforeClass;
import org.junit.Test;

public class SettingsTest {

    @BeforeClass
    public static void setUpClass() {
        XMLUnit.setIgnoreWhitespace(true);
    }

    @Test
    public void testMarshal() throws Exception {
        Settings settings = new Settings();
        settings.setTimeToUse(null);
        Writer writer = new StringWriter();
        JAXB.marshal(settings, writer);
        String expected = "<settings>"
                + "<daylightIntensity>100.0</daylightIntensity>"
                + "<displayUpdateInterval>5.0</displayUpdateInterval>"
                + "<dotsPerGridLine>15</dotsPerGridLine>"
                + "<fixedLatitude>0.0</fixedLatitude>"
                + "<fixedLongitude>0.0</fixedLongitude>"
                + "<gammaCorrection>1.0</gammaCorrection>"
                + "<gridColor>#ffffff</gridColor>"
                + "<gridLinesPerQuadrant>6</gridLinesPerQuadrant>"
                + "<gridVisible>false</gridVisible>"
                + "<imageHeight>600</imageHeight>"
                + "<imageMagnification>1.0</imageMagnification>"
                + "<imageProjection>ORTHOGRAPHIC</imageProjection>"
                + "<imageWidth>800</imageWidth>"
                + "<legendPosition>TOP_LEFT</legendPosition>"
                + "<legendVisible>false</legendVisible>"
                + "<markerColor>#ff0000</markerColor>"
                + "<markers>"
                + "  <marker>"
                + "    <latitude>61.17</latitude>"
                + "    <longitude>-150.0</longitude>"
                + "    <name>Anchorage</name>"
                + "  </marker>"
                + "  <marker>"
                + "    <latitude>38.0</latitude>"
                + "    <longitude>23.73</longitude>"
                + "    <name>Athens</name>"
                + "  </marker>"
                + "  <marker>"
                + "    <latitude>33.4</latitude>"
                + "    <longitude>44.4</longitude>"
                + "    <name>Baghdad</name>"
                + "  </marker>"
                + "  <marker>"
                + "    <latitude>13.73</latitude>"
                + "    <longitude>100.5</longitude>"
                + "    <name>Bangkok</name>"
                + "  </marker>"
                + "  <marker>"
                + "    <latitude>39.92</latitude>"
                + "    <longitude>116.43</longitude>"
                + "    <name>Beijing</name>"
                + "  </marker>"
                + "  <marker>"
                + "    <latitude>52.53</latitude>"
                + "    <longitude>13.42</longitude>"
                + "    <name>Berlin</name>"
                + "  </marker>"
                + "  <marker>"
                + "    <latitude>32.3</latitude>"
                + "    <longitude>-64.7</longitude>"
                + "    <name>Bermuda</name>"
                + "  </marker>"
                + "  <marker>"
                + "    <latitude>42.33</latitude>"
                + "    <longitude>-71.08</longitude>"
                + "    <name>Boston</name>"
                + "  </marker>"
                + "  <marker>"
                + "    <latitude>-15.8</latitude>"
                + "    <longitude>-47.9</longitude>"
                + "    <name>Brasilia</name>"
                + "  </marker>"
                + "  <marker>"
                + "    <latitude>-4.2</latitude>"
                + "    <longitude>15.3</longitude>"
                + "    <name>Brazzaville</name>"
                + "  </marker>"
                + "  <marker>"
                + "    <latitude>-34.67</latitude>"
                + "    <longitude>-58.5</longitude>"
                + "    <name>Buenos Aires</name>"
                + "  </marker>"
                + "  <marker>"
                + "    <latitude>31.05</latitude>"
                + "    <longitude>31.25</longitude>"
                + "    <name>Cairo</name>"
                + "  </marker>"
                + "  <marker>"
                + "    <latitude>22.5</latitude>"
                + "    <longitude>88.3</longitude>"
                + "    <name>Kolkata</name>"
                + "  </marker>"
                + "  <marker>"
                + "    <latitude>-33.93</latitude>"
                + "    <longitude>18.47</longitude>"
                + "    <name>Cape Town</name>"
                + "  </marker>"
                + "  <marker>"
                + "    <latitude>33.6</latitude>"
                + "    <longitude>-7.6</longitude>"
                + "    <name>Casablanca</name>"
                + "  </marker>"
                + "  <marker>"
                + "    <latitude>41.83</latitude>"
                + "    <longitude>-87.75</longitude>"
                + "    <name>Chicago</name>"
                + "  </marker>"
                + "  <marker>"
                + "    <latitude>32.78</latitude>"
                + "    <longitude>-96.8</longitude>"
                + "    <name>Dallas</name>"
                + "  </marker>"
                + "  <marker>"
                + "    <latitude>28.63</latitude>"
                + "    <longitude>77.2</longitude>"
                + "    <name>New Delhi</name>"
                + "  </marker>"
                + "  <marker>"
                + "    <latitude>39.75</latitude>"
                + "    <longitude>-105.0</longitude>"
                + "    <name>Denver</name>"
                + "  </marker>"
                + "  <marker>"
                + "    <latitude>24.23</latitude>"
                + "    <longitude>55.28</longitude>"
                + "    <name>Dubai</name>"
                + "  </marker>"
                + "  <marker>"
                + "    <latitude>-27.1</latitude>"
                + "    <longitude>-109.4</longitude>"
                + "    <name>Easter Island</name>"
                + "  </marker>"
                + "  <marker>"
                + "    <latitude>-18.0</latitude>"
                + "    <longitude>178.1</longitude>"
                + "    <name>Fiji</name>"
                + "  </marker>"
                + "  <marker>"
                + "    <latitude>13.5</latitude>"
                + "    <longitude>144.8</longitude>"
                + "    <name>Guam</name>"
                + "  </marker>"
                + "  <marker>"
                + "    <latitude>60.13</latitude>"
                + "    <longitude>25.0</longitude>"
                + "    <name>Helsinki</name>"
                + "  </marker>"
                + "  <marker>"
                + "    <latitude>22.2</latitude>"
                + "    <longitude>114.1</longitude>"
                + "    <name>Hong Kong</name>"
                + "  </marker>"
                + "  <marker>"
                + "    <latitude>21.32</latitude>"
                + "    <longitude>-157.83</longitude>"
                + "    <name>Honolulu</name>"
                + "  </marker>"
                + "  <marker>"
                + "    <latitude>52.2</latitude>"
                + "    <longitude>104.3</longitude>"
                + "    <name>Irkutsk</name>"
                + "  </marker>"
                + "  <marker>"
                + "    <latitude>41.0</latitude>"
                + "    <longitude>29.0</longitude>"
                + "    <name>Istanbul</name>"
                + "  </marker>"
                + "  <marker>"
                + "    <latitude>-6.13</latitude>"
                + "    <longitude>106.75</longitude>"
                + "    <name>Jakarta</name>"
                + "  </marker>"
                + "  <marker>"
                + "    <latitude>31.8</latitude>"
                + "    <longitude>35.2</longitude>"
                + "    <name>Jerusalem</name>"
                + "  </marker>"
                + "  <marker>"
                + "    <latitude>34.5</latitude>"
                + "    <longitude>69.2</longitude>"
                + "    <name>Kabul</name>"
                + "  </marker>"
                + "  <marker>"
                + "    <latitude>27.7</latitude>"
                + "    <longitude>85.3</longitude>"
                + "    <name>Kathmandu</name>"
                + "  </marker>"
                + "  <marker>"
                + "    <latitude>50.4</latitude>"
                + "    <longitude>30.5</longitude>"
                + "    <name>Kiev</name>"
                + "  </marker>"
                + "  <marker>"
                + "    <latitude>3.13</latitude>"
                + "    <longitude>101.7</longitude>"
                + "    <name>Kuala Lumpur</name>"
                + "  </marker>"
                + "  <marker>"
                + "    <latitude>6.45</latitude>"
                + "    <longitude>3.47</longitude>"
                + "    <name>Lagos</name>"
                + "  </marker>"
                + "  <marker>"
                + "    <latitude>-12.1</latitude>"
                + "    <longitude>-77.05</longitude>"
                + "    <name>Lima</name>"
                + "  </marker>"
                + "  <marker>"
                + "    <latitude>51.5</latitude>"
                + "    <longitude>-0.17</longitude>"
                + "    <name>London</name>"
                + "  </marker>"
                + "  <marker>"
                + "    <latitude>40.42</latitude>"
                + "    <longitude>-3.72</longitude>"
                + "    <name>Madrid</name>"
                + "  </marker>"
                + "  <marker>"
                + "    <latitude>14.6</latitude>"
                + "    <longitude>121.0</longitude>"
                + "    <name>Manila</name>"
                + "  </marker>"
                + "  <marker>"
                + "    <latitude>21.5</latitude>"
                + "    <longitude>39.8</longitude>"
                + "    <name>Mecca</name>"
                + "  </marker>"
                + "  <marker>"
                + "    <latitude>19.4</latitude>"
                + "    <longitude>-99.1</longitude>"
                + "    <name>Mexico City</name>"
                + "  </marker>"
                + "  <marker>"
                + "    <latitude>25.8</latitude>"
                + "    <longitude>-80.2</longitude>"
                + "    <name>Miami</name>"
                + "  </marker>"
                + "  <marker>"
                + "    <latitude>6.2</latitude>"
                + "    <longitude>-10.8</longitude>"
                + "    <name>Monrovia</name>"
                + "  </marker>"
                + "  <marker>"
                + "    <latitude>45.5</latitude>"
                + "    <longitude>-73.5</longitude>"
                + "    <name>Montreal</name>"
                + "  </marker>"
                + "  <marker>"
                + "    <latitude>55.75</latitude>"
                + "    <longitude>37.7</longitude>"
                + "    <name>Moscow</name>"
                + "  </marker>"
                + "  <marker>"
                + "    <latitude>-1.28</latitude>"
                + "    <longitude>36.83</longitude>"
                + "    <name>Nairobi</name>"
                + "  </marker>"
                + "  <marker>"
                + "    <latitude>59.93</latitude>"
                + "    <longitude>10.75</longitude>"
                + "    <name>Oslo</name>"
                + "  </marker>"
                + "  <marker>"
                + "    <latitude>48.87</latitude>"
                + "    <longitude>2.33</longitude>"
                + "    <name>Paris</name>"
                + "  </marker>"
                + "  <marker>"
                + "    <latitude>-32.0</latitude>"
                + "    <longitude>115.9</longitude>"
                + "    <name>Perth</name>"
                + "  </marker>"
                + "  <marker>"
                + "    <latitude>45.5</latitude>"
                + "    <longitude>-122.5</longitude>"
                + "    <name>Portland</name>"
                + "  </marker>"
                + "  <marker>"
                + "    <latitude>-0.2</latitude>"
                + "    <longitude>-78.5</longitude>"
                + "    <name>Quito</name>"
                + "  </marker>"
                + "  <marker>"
                + "    <latitude>64.15</latitude>"
                + "    <longitude>-21.97</longitude>"
                + "    <name>Reykjavik</name>"
                + "  </marker>"
                + "  <marker>"
                + "    <latitude>-22.88</latitude>"
                + "    <longitude>-43.28</longitude>"
                + "    <name>Rio de Janeiro</name>"
                + "  </marker>"
                + "  <marker>"
                + "    <latitude>41.88</latitude>"
                + "    <longitude>12.5</longitude>"
                + "    <name>Rome</name>"
                + "  </marker>"
                + "  <marker>"
                + "    <latitude>11.0</latitude>"
                + "    <longitude>106.7</longitude>"
                + "    <name>Ho Chi Minh City</name>"
                + "  </marker>"
                + "  <marker>"
                + "    <latitude>37.75</latitude>"
                + "    <longitude>-122.45</longitude>"
                + "    <name>San Francisco</name>"
                + "  </marker>"
                + "  <marker>"
                + "    <latitude>9.98</latitude>"
                + "    <longitude>-84.07</longitude>"
                + "    <name>San Jose</name>"
                + "  </marker>"
                + "  <marker>"
                + "    <latitude>18.5</latitude>"
                + "    <longitude>-66.1</longitude>"
                + "    <name>San Juan</name>"
                + "  </marker>"
                + "  <marker>"
                + "    <latitude>-33.5</latitude>"
                + "    <longitude>-70.7</longitude>"
                + "    <name>Santiago</name>"
                + "  </marker>"
                + "  <marker>"
                + "    <latitude>1.2</latitude>"
                + "    <longitude>103.9</longitude>"
                + "    <name>Singapore</name>"
                + "  </marker>"
                + "  <marker>"
                + "    <latitude>42.67</latitude>"
                + "    <longitude>23.3</longitude>"
                + "    <name>Sofia</name>"
                + "  </marker>"
                + "  <marker>"
                + "    <latitude>59.33</latitude>"
                + "    <longitude>18.08</longitude>"
                + "    <name>Stockholm</name>"
                + "  </marker>"
                + "  <marker>"
                + "    <latitude>-33.92</latitude>"
                + "    <longitude>151.17</longitude>"
                + "    <name>Sydney</name>"
                + "  </marker>"
                + "  <marker>"
                + "    <latitude>-17.6</latitude>"
                + "    <longitude>-149.5</longitude>"
                + "    <name>Tahiti</name>"
                + "  </marker>"
                + "  <marker>"
                + "    <latitude>16.8</latitude>"
                + "    <longitude>-3.0</longitude>"
                + "    <name>Timbuktu</name>"
                + "  </marker>"
                + "  <marker>"
                + "    <latitude>35.67</latitude>"
                + "    <longitude>139.75</longitude>"
                + "    <name>Tokyo</name>"
                + "  </marker>"
                + "  <marker>"
                + "    <latitude>43.7</latitude>"
                + "    <longitude>-79.42</longitude>"
                + "    <name>Toronto</name>"
                + "  </marker>"
                + "  <marker>"
                + "    <latitude>32.9</latitude>"
                + "    <longitude>13.2</longitude>"
                + "    <name>Tripoli</name>"
                + "  </marker>"
                + "  <marker>"
                + "    <latitude>47.9</latitude>"
                + "    <longitude>106.9</longitude>"
                + "    <name>Ulan Bator</name>"
                + "  </marker>"
                + "  <marker>"
                + "    <latitude>49.22</latitude>"
                + "    <longitude>-123.1</longitude>"
                + "    <name>Vancouver</name>"
                + "  </marker>"
                + "  <marker>"
                + "    <latitude>48.22</latitude>"
                + "    <longitude>16.37</longitude>"
                + "    <name>Vienna</name>"
                + "  </marker>"
                + "  <marker>"
                + "    <latitude>38.9</latitude>"
                + "    <longitude>-77.0</longitude>"
                + "    <name>Washington</name>"
                + "  </marker>"
                + "  <marker>"
                + "    <latitude>-41.28</latitude>"
                + "    <longitude>174.78</longitude>"
                + "    <name>Wellington</name>"
                + "  </marker>"
                + "  <marker>"
                + "    <latitude>62.5</latitude>"
                + "    <longitude>-114.3</longitude>"
                + "    <name>Yellowknife</name>"
                + "  </marker>"
                + "  <marker>"
                + "    <latitude>90.0</latitude>"
                + "    <longitude>0.0</longitude>"
                + "    <name>North Pole</name>"
                + "  </marker>"
                + "  <marker>"
                + "    <latitude>-90.0</latitude>"
                + "    <longitude>0.0</longitude>"
                + "    <name>South Pole</name>"
                + "  </marker>"
                + "</markers>"
                + "<markersVisible>true</markersVisible>"
                + "<nightIntensity>5.0</nightIntensity>"
                + "<orbitInclination>0.0</orbitInclination>"
                + "<orbitPeriod>1.0</orbitPeriod>"
                + "<percentBigStars>0.0</percentBigStars>"
                + "<quakeColor>#ffff00</quakeColor>"
                + "<quakes>"
                + "</quakes>"
                + "<quakesFeedURL>http://earthquake.usgs.gov/earthquakes/feed/v1.0/summary/significant_week.csv</quakesFeedURL>"
                + "<quakesUpdateInterval>3</quakesUpdateInterval>"
                + "<quakesVisible>false</quakesVisible>"
                + "<shadingVisible>true</shadingVisible>"
                + "<starFrequency>0.002</starFrequency>"
                + "<starsVisible>true</starsVisible>"
                + "<sunLatitude>0.0</sunLatitude>"
                + "<sunLongitude>0.0</sunLongitude>"
                + "<sunRelativeLatitude>0.0</sunRelativeLatitude>"
                + "<sunRelativeLongitude>0.0</sunRelativeLongitude>"
                + "<sunUseActualPosition>true</sunUseActualPosition>"
                + "<terminatorFallOff>1.0</terminatorFallOff>"
                + "<timeUseCurrent>true</timeUseCurrent>"
                + "<timeWarpFactor>1.0</timeWarpFactor>"
                + "<useScreenSize>false</useScreenSize>"
                + "<viewpointType>DEFAULT</viewpointType>"
                + "</settings>";
        XMLAssert.assertXMLEqual(expected, writer.toString());
    }
}
